version: "3"
services:

  mysqldb:
    image: "mysql/mysql-server:5.7"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=annual_leave