app:
  name: Annual Leave
  api:
    title: Annual Leave APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.example.demo.controllers
    contact-name: Evion Cane
    contact-email: evioncane@gmail.com
    swagger:
      enable: true

spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3307/annual_leave?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: user
    password: user
    platform: mysql
    initialization-mode: always
    data: classpath:sql/data.sql

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

security:
  config:
    jwtSecret: secret
    jwtExpirationMs: 86400000
