app:
  name: Annual Leave
  api:
    title: Annual Leave APIs
    version: 1.0.0
    description: Spring Boot APIs description
    base-package: com.example.demo.handlers
    contact-name: apisupportgroup
    contact-email: apisupportgroup@abc.com
    swagger:
      enable: true

spring:
  datasource:
    url: jdbc:mysql://0.0.0.0:3307/annual_leave?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: user
    password: user
    platform: mysql
    initialization-mode: always
